### PR TITLE
[WIP] upgrade to EVMC 7.1.0

### PR DESCRIPTION
**Pull request by jangko**
- [x] update examples
- [x] add tests
- [x] add CI test
- [x] implement high level convenience API for Nim

### CODE REVIEW

**Review by zah — APPROVED** [review]
That looks great, @jangko.
Feel free to merge it when the Travis builds become green. If the errors look cryptic, @stefantalpalaru might help with more information regarding the existing setup.

**Comment by stefantalpalaru** [comment]
> error: invalid argument '-std=c++11' not allowed with 'C'

Clang is right to complain. You're asking for a C++ standard from a C compiler. Try `-std=c11` instead.

**Comment by jangko** [comment]
Turn out it's a nim cpp codegen bug. When we request explicit function pointer casting, the codegen does not generate any cast. Clang compiler will protest with an error, but GCC seems allow implicit function pointer conversion.

looking for a workaround.

**Comment by stefantalpalaru** [comment]
Do we really have to use the C++ backend? It's not tested as much as the C one.

**Comment by jangko** [comment]
it's far much easier turn a C file into CPP than turn a CPP into C.
and in nimbus, we will not using any cpp.
the cpp is only used for testing the ABI in this repo.

**Comment by axic** [comment]
> Do we really have to use the C++ backend? It's not tested as much as the C one.

Just curious: what do you mean exactly? Have you looked at the coverage reports? The C++ interface is used by Aleth and Solidity.

**Comment by stefantalpalaru** [comment]
> Just curious: what do you mean exactly?

I'm talking about the Nim compiler's backend.

**Comment by axic** [comment]
Ah my bad!

**Comment by arnetheduck** [comment]
Ideally we stick with C backend since that is what we use elsewhere..

**Pull request merged**
